name: compound_flooding
channels:
  - rapidsai
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cudatoolkit=11.2
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  - xarray>=0.19.0
  - matplotlib>=3.4.0
  - cartopy>=0.20.0
  - dask>=2021.10.0
  - netcdf4>=1.5.7
  - pytest>=6.2.5

  # Dev dependencies
  - black>=21.9b0
  - isort>=5.9.3
  - mypy>=0.910
  - flake8>=3.9.2
  - pytest-cov>=2.12.1

  # GPU dependencies (cuDF requires newer version for Python 3.10)
  - cudf=23.02

  # Pip dependencies fallback (optional, for packages only available via pip)
  - pip
  - pip:
      # If anything needs to be installed via pip only, add here
      # Example:
      # - some-package-not-on-conda
      - "setuptools>=42"
      - "wheel"
